<?php
// $Id$

// --------------------------------------------------------------------------
// Drupal Hooks

function nodequeue_help($section = "admin/help#nodequeue") {
  switch ($section) {
    case 'admin/help#nodequeue':
      $output = t("The nodequeue module enables putting nodes into manual queues.");
      break;

    case 'admin/modules#description':
      $output = t("The nodequeue module enables putting nodes into manual queues.");
      break;
  }

  return $output;
}

function nodequeue_perm() {
  return array ('manipulate queues', 'administer nodequeue');
}

function nodequeue_menu($may_cache) {
  $items = array();
  global $user;

  if ($may_cache) {
    // administrative items
    $access = user_access('administer nodequeue');
    $items[] = array(
      'path' => 'admin/nodequeue',
      'title' => t('node queue'),
      'access' => $access,
      'callback' => 'nodequeue_admin',
      'type' => MENU_NORMAL_ITEM
    );
    $items[] = array(
      'path' => 'admin/nodequeue/list',
      'title' => t('list'),
      'access' => $access,
      'callback' => 'nodequeue_admin',
      'weight' => -1,
      'type' => MENU_DEFAULT_LOCAL_TASK
    );
    $items[] = array(
      'path' => 'admin/nodequeue/add',
      'title' => t('add'),
      'access' => $access,
      'callback' => 'nodequeue_admin_edit',
      'type' => MENU_LOCAL_TASK
    );
    $items[] = array(
      'path' => 'admin/nodequeue/delete',
      'title' => t('add'),
      'access' => $access,
      'callback' => 'nodequeue_admin_delete',
      'type' => MENU_CALLBACK
    );
  }
  else {
		$arg1 = (int) arg(1);
    if ($user && arg(0) == 'node' && is_numeric($arg1) && $arg1 > 0 && ($access = user_access('manipulate queues'))) {
      $node = node_load($arg1);
      $items[] = array(
        'path' => 'node/' . $arg1 . '/nodequeue',
        'title' => t('nodequeue'),
        'access' => $access,
        'callback' => 'nodequeue_page',
        'callback arguments' => array($arg1),
        'type' => MENU_LOCAL_TASK,
        'weight' => 5
      );
    }
  }
  return $items;
}

// --------------------------------------------------------------------------
// Nodequeue Admin pages

/**
 * menu callback
 */
function nodequeue_page($nid) {
  $node = node_load($nid);
  drupal_set_title($node->title);

  if(!nodequeue_node_access($node->type)) {
    return t('No node queue defined for this node type.');
  }
  else {
    $op = (string) arg(3);
    $qid = (int) arg(4);

    if ($op && $qid) {
      $queue = _nodequeue_load($qid);
      if ($op == 'add') {
        _nodequeue_queue_add($queue, $nid);
      }
      elseif ($op == 'remove') {
        _nodequeue_queue_remove($queue, $pos);
      }
      drupal_goto("node/$nid/nodequeue");
    }
    return nodequeue_page_form($node);
  }
}

function nodequeue_page_form($node) {
  // Determine which queues are appropriate for this nodetype.
  global $user;

  $roles = array_keys($user->roles) + array(DRUPAL_AUTHENTICATED_RID);
  $role_args = array_fill(0, count($roles), '%d');

  $result = db_query(db_rewrite_sql("SELECT nq.qid, nq.title, nq.size, COUNT(DISTINCT(nqn.nid)) AS numnodes FROM {nodequeue_queue} nq INNER JOIN {nodequeue_types} nt ON nt.qid = nq.qid LEFT JOIN {nodequeue_nodes} nqn ON nqn.qid = nq.qid INNER JOIN {nodequeue_roles} nr ON nr.qid = nq.qid WHERE nt.type = '%s' AND nr.rid IN (". implode(',', $role_args) .") GROUP BY nq.qid, nqn.nid ORDER BY nq.title", 'nq', 'qid'), array_merge(array($node->type), $roles));

  $form = array();
  while ($queue = db_fetch_object($result)) {
    $form['title'][$queue->qid] = array('#type' => 'markup', '#value' => $queue->title);
    $form['size'][$queue->qid] = array('#type' => 'markup', '#value' => $queue->size);
    $form['numnodes'][$queue->qid] = array('#type' => 'markup', '#value' => $queue->numnodes . ($queue->size && $queue->size == $queue->numnodes ? ' '. t('QUEUE FULL') : ''));

    $ops = array(l(t('view queue'), "admin/nodequeue/view/$queue->qid"));

    if (is_numeric($pos = db_result(db_query("SELECT position FROM {nodequeue_nodes} WHERE nid = %d AND qid = %d", $node->nid, $queue->qid)))) {
      $ops[] = l(t("remove from queue"), "node/$node->nid/nodequeue/remove/$queue->qid/$pos");
    }
    else {
      $ops[] = l(t("add to queue"), "node/$node->nid/nodequeue/add/$queue->qid");
    }

    $form['operations'][$queue->qid] = array('#type' => 'markup', '#value' => theme('links', $ops));
  }

  return drupal_get_form('nodequeue_page_form', $form);
}

function theme_nodequeue_page_form($form) {
  $header = array(t('Title'), t('Max Nodes'), t('In queue'), t('Operation'));
  foreach (element_children($form['title']) as $key) {
    $row = array();
    $row[] = form_render($form['title'][$key]);
    $row[] = array('data' => form_render($form['size'][$key]), 'align' => 'right');
    $row[] = array('data' => form_render($form['numnodes'][$key]), 'align' => 'right');
    $row[] = form_render($form['operations'][$key]);
    $rows[] = $row;
  }
  $output .= theme('table', $header, $rows);
  $output .= form_render($form);
  return $output;
}

function nodequeue_admin($arg = '', $arg2 = '', $arg3 = '', $arg4 = '') {
  if ($arg == 'edit') {
    return nodequeue_admin_edit($arg2);
  }
  if ($arg == 'view') {
    return nodequeue_admin_view($arg2, $arg3, $arg4);
  }

  $result = pager_query('SELECT nq.*, COUNT(DISTINCT(nn.nid)) as nodes FROM {nodequeue_queue} nq LEFT JOIN {nodequeue_nodes} nn ON nq.qid = nn.qid GROUP by nq.title', 20, 0, 'SELECT COUNT(q.qid) FROM {nodequeue_queue} q');

  if (db_num_rows($result)) {
    $header = array(t('Title'), t('Max Nodes'), t('In Queue'), t('Operation'));

    $rows = array();
    while ($queue = db_fetch_object($result)) {
      $rows[] = array(
        $queue->title,
        array('data' => $queue->size, 'align' => 'right'),
        array('data' => $queue->nodes, 'align' => 'right'),
        array('data' => theme('links', array(l(t('edit'), "admin/nodequeue/edit/$queue->qid"), l(t('view'), "admin/nodequeue/view/$queue->qid"), l(t('delete'), "admin/nodequeue/delete/$queue->qid"))))
        );
    }

    $output = theme('table', $header, $rows);
    $output .= theme('pager', NULL, 20);

    return  $output;
  }
  else {
    return t('No node queues exist.');
  }

}

//
// render queue add or edit page, and/or handle results
//
function nodequeue_admin_edit($qid = 0) {
  $which = arg(2);
  if ($which == 'edit' && (!is_numeric($qid) || $qid == 0))  {
    return drupal_access_denied();
  }

  $output = '';

  if ($which == 'edit') {
    $output = nodequeue_queue_form(_nodequeue_load($qid));
  }
  else {
    $output = nodequeue_queue_form();
  }

  return $output;
}

//
// display add/edit queue form
//
function nodequeue_queue_form($queue = array()) {

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => $queue->title,
    '#size' => 50,
    '#maxlength' => 64,
    '#description' => t('Enter the name of the queue'),
  );

  $form['size'] = array(
    '#type' => 'textfield',
    '#title' => t('Queue Size'),
    '#default_value' => $queue->size,
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('The maximum number of nodes will appear in the queue. Enter 0 for no limit'),
  );

  $result = db_query("SELECT * FROM {role} ORDER BY name");
  while ($role = db_fetch_object($result)) {
    $roles[$role->rid] = $role->name;
  }

  $form['roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Roles'),
    '#default_value' => $queue->roles,
    '#options' => $roles,
    '#description' => t('Check each role that can add nodes to the queue.'),
  );

  foreach (node_get_types() as $type => $name) {
    $nodes[$type] = $name;
  }
  $form['types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Types'),
    '#default_value' => $queue->types,
    '#options' => $nodes,
    '#description' => t('Check each node type that can be added to this queue.'),
  );


  $form[] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  if ($queue->qid) {
    $form[] = array(
      '#type' => 'submit',
      '#value' => t('Delete'),
    );
    $form['qid'] = array(
      '#type' => 'value',
      '#value' => $queue->qid,
    );
    $form['count'] = array(
      '#type' => 'value',
      '#value' => $queue->count,
    );
  }

  return drupal_get_form('nodequeue_edit', $form);
}

function nodequeue_edit_submit($formid, $form) {
  if ($_POST['op'] == t('Delete')) {
    return drupal_goto("admin/nodequeue/delete/$form[qid]");
  }

  $queue = (object) $form;
  // fix checkboxes; sigh
  foreach ($queue->roles as $role => $value) {
    if ($value) {
      $roles[] = $role;
    }
  }
  $queue->roles = $roles;

  foreach ($queue->types as $type => $value) {
    if ($value) {
      $types[] = $type;
    }
  }
  $queue->types = $types;

  _nodequeue_save($queue);
  if ($queue->size) // 0 means "don't care"
    _nodequeue_check_queuesize($queue);
  drupal_set_message(t('The queue has been updated.'));
  drupal_goto('admin/nodequeue');
}

function nodequeue_admin_delete($qid) {
  $queue = _nodequeue_load($qid);

  if (!$queue)
    return drupal_goto('admin/nodequeue');

  $form['qid'] = array('#type' => 'value', '#value' => $queue->qid);
  return confirm_form('nodequeue_delete_confirm', $form,
    t('Are you sure you want to delete "%title"?', array('%title' => $queue->title)),
    $_GET['destination'] ? $_GET['destination'] : 'admin/nodequeue',
    t('This action cannot be undone.'),
    t('Delete'), t('Cancel')
  );
}

function nodequeue_delete_confirm_submit($formid, $form) {
  if ($form['confirm']) {
    _nodequeue_delete($form['qid']);
    drupal_set_message("The queue has been deleted.");
    drupal_goto('admin/nodequeue');
  }
}

// View a node queue and move items up or down.
function nodequeue_admin_view($qid, $op, $pos) {
  $qid = intval($qid);
  $queue = _nodequeue_load($qid);
  $pos = intval($pos);

  if ($op == 'up') {
    nodequeue_queue_up($queue, $pos);
    return drupal_goto("admin/nodequeue/view/$qid");
  }
  if ($op == 'front') {
    nodequeue_queue_front($queue, $pos);
    return drupal_goto("admin/nodequeue/view/$qid");
  }
  if ($op == 'down') {
    nodequeue_queue_down($queue, $pos);
    return drupal_goto("admin/nodequeue/view/$qid");
  }
  if ($op == 'back') {
    nodequeue_queue_back($queue, $pos);
    return drupal_goto("admin/nodequeue/view/$qid");
  }
  if ($op == 'remove') {
    _nodequeue_queue_remove($queue, $pos);
    return drupal_goto("admin/nodequeue/view/$qid");
  }
  if ($op == 'clear') {
    $form['qid'] = array('#type' => 'value', '#value' => $queue->qid);
    return confirm_form('nodequeue_clear_confirm', $form,
      t('Clearing queue "%s" is irreversible. You sure?', array('%s' => $queue->title)),
      $_GET['destination'] ? $_GET['destination'] : "admin/nodequeue/$qid/clear",
      t('This action cannot be undone.'),
      t('Clear Queue'), t('Cancel')
    );
  }

  drupal_set_title("Nodequeue '$queue->title'");
  $output = '';

  $sql = "SELECT DISTINCT(n.nid), n.title, n.uid, u.name, n.created, nq.position FROM {node} n LEFT JOIN {users} u on n.uid = u.uid LEFT JOIN {nodequeue_nodes} nq ON nq.nid = n.nid WHERE nq.qid = $qid ORDER BY nq.position";

  // Don't rewrite because a queue manager has to be able to move items up
  // and down in the queue even if they can't be viewed.
//  $sql = db_rewrite_sql($sql);
  $result = pager_query($sql, 25, 0);

  if (db_num_rows($result) > 0) {
    while ($node = db_fetch_object($result)) {
      $buttons = l(theme('image', drupal_get_path('module', 'nodequeue') .'/go-up.png', t('move up')), "admin/nodequeue/view/$qid/up/$node->position", array('title'=>t('move up')), NULL, NULL, FALSE, TRUE);
      $buttons .= l(theme('image', drupal_get_path('module', 'nodequeue') .'/go-down.png', t('move down')), "admin/nodequeue/view/$qid/down/$node->position", array('title'=>t('move down')), NULL, NULL, FALSE, TRUE);
      $buttons .= l(theme('image', drupal_get_path('module', 'nodequeue') .'/go-top.png', t('move to front')), "admin/nodequeue/view/$qid/front/$node->position", array('title'=>t('move to front')), NULL, NULL, FALSE, TRUE);
      $buttons .= l(theme('image', drupal_get_path('module', 'nodequeue') .'/go-bottom.png', t('move to back')), "admin/nodequeue/view/$qid/back/$node->position", array('title'=>t('move to back')), NULL, NULL, FALSE, TRUE);
      $buttons .= l(theme('image', drupal_get_path('module', 'nodequeue') .'/user-trash.png', t('remove from queue')), "admin/nodequeue/view/$qid/remove/$node->position", array('title'=>t('remove from queue')), NULL, NULL, FALSE, TRUE);
      $list[] = array(l($node->title, "node/$node->nid"), theme('username', $node), format_date($node->created), $buttons);
    }
    $output .= theme('table', array("Node", "Author", "Date", "Operation"), $list, array('width' => '100%'));
    $output .= theme('pager', NULL, 25);
    $output .= "<p>" . l(t("Empty this queue"), "admin/nodequeue/view/$qid/clear") . "</p>";
  }
  else {
    $output .= t('<p>Queue is empty!</p>');
  }

  return $output;
}

function nodequeue_clear_confirm_submit($formid, $form) {
  if ($form['confirm']) {
    nodequeue_queue_clear($form['qid']);
    return drupal_goto("admin/nodequeue/view/$form[qid]");
  }
}

function nodequeue_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch($op) {
    case 'delete':
      // If a node is being deleted, ensure it's also removed from any queues.
      db_query("DELETE FROM {nodequeue_nodes} WHERE nid=%d", $node->nid);
      break;
  }
}

// --------------------------------------------------------------------------
// Database manipulation functions

/**
 * Return TRUE if $user can
 * control the queue for this node.
 */
function nodequeue_node_access($type) {
  global $user;

  $sql = 'SELECT nq.qid FROM {nodequeue_queue} nq INNER JOIN {nodequeue_roles} nr ON nr.qid = nq.qid INNER JOIN {nodequeue_types} nt ON nt.qid = nq.qid ';

  // superuser always has access.
  if ($user->uid == 1) {
    $sql .= "WHERE nt.type = '%s'";
    $result = db_query($sql, $type);
  }
  else {
    $roles = array_keys($user->roles) + array(DRUPAL_AUTHENTICATED_RID);
    $role_args = array_fill(0, count($roles), '%d');

    $sql .= "WHERE nr.rid IN (". implode(',', $role_args) .") AND nt.type = '%s'";
    $result = db_query($sql, array_merge($roles, array($type)));
  }

  return db_num_rows($result);
}

function _nodequeue_load($qid, $nodes = false) {
  $queue = db_fetch_object(db_query("SELECT * FROM {nodequeue_queue} WHERE qid = %d", $qid));
  if ($queue) {
    $result = db_query("SELECT rid FROM {nodequeue_roles} WHERE qid = %d", $qid);
    while ($obj = db_fetch_object($result))
      $queue->roles[] = $obj->rid;

    $result = db_query("SELECT type FROM {nodequeue_types} WHERE qid = %d", $qid);
    while ($obj = db_fetch_object($result))
      $queue->types[] = $obj->type;

    $queue->count = db_result(db_query("SELECT count(*) from {nodequeue_nodes} where qid = %d", $qid));

    if ($nodes) {
      $result = db_query("SELECT nid FROM {nodequeue_nodes} WHERE qid = $qid ORDER BY position");
      while ($obj = db_fetch_object($result)) {
        $queue->nodes[] = $obj->nid;
      }
    }
  }
  return $queue;
}

function _nodequeue_save($queue, $nodes = false) {
  $queue->size = intval($queue->size);
  $title = db_escape_string($queue->title);
  if (!$queue->qid) {
    $queue->qid = db_next_id("{nodequeue_queue}_qid");
    db_query("INSERT INTO {nodequeue_queue} (qid, title, size) VALUES (%d, '%s', %d)", $queue->qid, $title, $queue->size);
  }
  else {
    $queue->qid = intval($queue->qid);
    db_query("UPDATE {nodequeue_queue} set size = %d, title = '%s' WHERE qid = %d", $queue->size, $title, $queue->qid);
    db_query("DELETE FROM {nodequeue_roles} WHERE qid = %d", $queue->qid);
    db_query("DELETE FROM {nodequeue_types} WHERE qid = %d", $queue->qid);
    if ($nodes) {
      db_query("DELETE FROM {nodequeue_nodes} WHERE qid = %d", $queue->qid);
    }
  }


  if (is_array($queue->roles))
    foreach($queue->roles as $rid)
      db_query("INSERT INTO {nodequeue_roles} (qid, rid) VALUES (%d, %d)", $queue->qid, $rid);

  if (is_array($queue->types))
    foreach($queue->types as $type)
    db_query("INSERT INTO {nodequeue_types} (qid, type) VALUES (%d, '%s')", $queue->qid, $type);

  if ($nodes && is_array($queue->nodes))
    foreach($queue->nodes as $nid) {
      db_query("INSERT INTO {nodequeue_roles} (qid, nid, position) VALUES (%d, %d, %d)", $queue->qid, $nid, ++$position);

      // Stop if we somehow have more nodes in the queue than are allowed.
      if ($position >= $queue->size)
        break;
    }

  return $queue->qid;
}

function _nodequeue_delete($qid) {
  db_query("DELETE FROM {nodequeue_queue} WHERE qid = %d", $qid);
  db_query("DELETE FROM {nodequeue_roles} WHERE qid = %d", $qid);
  db_query("DELETE FROM {nodequeue_types} WHERE qid = %d", $qid);
  db_query("DELETE FROM {nodequeue_nodes} WHERE qid = %d", $qid);
}


// --------------------------------------------------------------------------
// Queue position control

function nodequeue_queue_swap($queue, $pos1, $pos2) {
  // Grab the nid off one of the positions so we can more easily swap.
  $nid = db_result(db_query("SELECT nid FROM {nodequeue_nodes} WHERE qid = %d AND position = %d", $queue->qid, $pos1));
  if (!$nid) {
    return;
  }

  db_query("UPDATE {nodequeue_nodes} SET position = %d WHERE position = %d AND qid = %d", $pos1, $pos2,  $queue->qid);
  db_query("UPDATE {nodequeue_nodes} SET position = %d WHERE nid = %d AND qid = %d", $pos2, $nid, $queue->qid);
}

function nodequeue_queue_up($queue, $position) {
  if ($position < 2 || $position > $queue->count)
    return;
  nodequeue_queue_swap($queue, $position - 1, $position);
}

function nodequeue_queue_down($queue, $position) {
  if ($position < 1 || $position >= $queue->count)
    return;
  nodequeue_queue_swap($queue, $position + 1, $position);
}

function nodequeue_queue_front($queue, $position) {
  if ($position < 2 || $position > $queue->count)
    return;
  $entry = db_fetch_object(db_query("SELECT * FROM {nodequeue_nodes} WHERE qid= %d AND position = %d", $queue->qid, $position));
  db_query("DELETE FROM {nodequeue_nodes} WHERE qid = %d AND position = %d", $queue->qid, $position);
  db_query("UPDATE {nodequeue_nodes} SET position = position + 1 WHERE qid= %d AND position < %d", $queue->qid, $position);
  db_query("INSERT INTO {nodequeue_nodes} (qid, nid, position) VALUES (%d, %d, 1)", $queue->qid, $entry->nid);
}

function nodequeue_queue_back($queue, $position) {
  if ($position < 1 || $position >= $queue->count)
    return;
  $entry = db_fetch_object(db_query("SELECT * FROM {nodequeue_nodes} WHERE qid = %d AND position = %d", $queue->qid, $position));
  db_query("DELETE FROM {nodequeue_nodes} WHERE qid = %d AND position = %d", $queue->qid, $position);
  db_query("UPDATE {nodequeue_nodes} SET position = position - 1 WHERE qid = %d AND position > %d", $queue->qid, $position);
  db_query("INSERT INTO {nodequeue_nodes} (qid, nid, position) VALUES (%d, %d, %d)", $queue->qid, $entry->nid, $queue->count);
}

function _nodequeue_queue_remove(&$queue, $start, $end = 0) {
  if (!$end)
    $end = $start;

  $diff = $end - $start + 1;
  db_query("DELETE FROM {nodequeue_nodes} WHERE qid = %d AND position >= %d AND position <= %d", $queue->qid, $start, $end);
  db_query("UPDATE {nodequeue_nodes} SET position = position - %d WHERE qid = %d AND position > %d",  $diff, $queue->qid, $end);

  $queue->count -= $diff;
}

function _nodequeue_queue_add(&$queue, $nid) {
  // Check for uniqueness
  if (db_result(db_query("SELECT nid from {nodequeue_nodes} WHERE qid = %d AND nid = %d", $queue->qid, $nid))) {
    return;
  }

  // Really, it should never happen that a queue gets bigger than is possible,
  // but just in case.
  if ($queue->size) // 0 means infinity so never do this if false
    _nodequeue_check_queuesize($queue, $queue->size - 1);

  $nid = intval($nid);
  $queue->count++;
  db_query("INSERT INTO {nodequeue_nodes} (qid, nid, position) VALUES (%d, %d, %d)", $queue->qid, $nid, $queue->count);
}

function nodequeue_queue_clear($qid) {
  db_query("DELETE FROM {nodequeue_nodes} WHERE qid = %d", $qid);
}

function _nodequeue_check_queuesize(&$queue, $size = 0) {
  if (!$size)
    $size = $queue->size;
  if ($queue->count > $size) {
    _nodequeue_queue_remove($queue, 1, $queue->count - $size);
  }
}

// --------------------------------------------------------------------------
// Actions module

function action_nodequeue_add($op, $edit = array(), $node) {
  switch($op) {
    case 'metadata':
      return array(
        'description' => t('Add to Node Queue'),
        'type' => t('node'),
        'batchable' => true,
        'configurable' => true,
      );
      break;

    case 'do':
      $qid = $edit['qid'];
      nodequeue_queue_add($qid, $node->nid);
      break;

    // return an HTML config form for the action
    case 'form':
      // default values for form
      if (!isset($edit['qid'])) $edit['qid'] = '';

      $result = db_query("SELECT * from {nodequeue_queue} ORDER BY title");
      while ($obj = db_fetch_object($result))
        $queues[$obj->qid] = $obj->title;

      // add form components
      $form['qid'] = array(
        '#type' => 'select',
        '#title' => t("Queue"),
        '#default_value' => $edit['qid'],
        '#options' => $queues,
      );
      return $form;

     // validate the HTML form

    // process the HTML form to store configuration
    case 'submit':
      $params = array(
        'qid' => $edit['qid']
      );
      return $params;
      break;
  }
}

function action_nodequeue_remove($op, $edit = array(), $node) {
  switch($op) {
    case 'metadata':
      return array(
        'description' => t('Remove from Node Queue'),
        'type' => t('node'),
        'batchable' => true,
        'configurable' => true,
      );
      break;

    case 'do':
      $qid = $edit['qid'];
      nodequeue_queue_remove_node($qid, $node->nid);
      break;

    // return an HTML config form for the action
    case 'form':
      // default values for form
      if (!isset($edit['qid'])) $edit['qid'] = '';

      $result = db_query("SELECT * from {nodequeue_queue} ORDER BY title");
      while ($obj = db_fetch_object($result))
        $queues[$obj->qid] = $obj->title;

      // add form components
      $form['qid'] = array(
        '#type' => 'select',
        '#title' => t("Queue"),
        '#default_value' => $edit['qid'],
        '#options' => $queues,
      );
      return $form;
      break;

     // validate the HTML form

    // process the HTML form to store configuration
    case 'submit':
      $params = array(
        'qid' => $edit['qid']
      );
      return $params;
      break;
  }
}

// --------------------------------------------------------------------------
// External queue fetching

function nodequeue_node_titles($qid, $title = '', $backward = true, $from = 0, $count = 0) {
  $orderby = ($backward ? "DESC" : "ASC");
  $sql = db_rewrite_sql("SELECT n.nid, n.title FROM {node} n LEFT JOIN {nodequeue_nodes} nn ON n.nid = nn.nid WHERE nn.qid = %d AND n.status = 1 ORDER BY nn.position $orderby");
  if ($count) {
    $result = db_query_range($sql, $qid, $from, $count);
  }
  else {
    $result = db_query($sql, $qid);
  }
  return node_title_list($result, $title);
}

function nodequeue_nodes($qid, $backward = true, $teaser = true, $links = true, $from = 0, $count = 0) {
  $orderby = ($backward ? "DESC" : "ASC");
  $sql = db_rewrite_sql("SELECT n.nid FROM {node} n INNER JOIN {nodequeue_nodes} nn ON n.nid = nn.nid WHERE nn.qid = %d AND n.status = 1 ORDER BY nn.position $orderby");
  if ($count) {
    $result = db_query_range($sql, $qid, $from, $count);
  }
  else {
    $result = db_query($sql, $qid);
  }

  while ($nid = db_fetch_object($result)) {
    $node = node_load($nid->nid);
    $output .= node_view($node, $teaser, false, $links);
  }
  return $output;
}

function nodequeue_fetch_front($qid, $teaser = true, $links = true) {
  return nodequeue_nodes($qid, false, $teaser, $links, 0, 1);
}

function nodequeue_fetch_back($qid, $teaser = true, $links = true) {
  $size = db_result(db_query("SELECT size FROM {nodequeue_nodes} WHERE qid = %d", $qid));
  return nodequeue_nodes($qid, false, $teaser, $links, $size - 1, 1);
}

function nodequeue_fetch_random($qid, $teaser = true, $links = true) {
  $count = db_result(db_query("SELECT count(*) FROM {nodequeue_nodes} WHERE qid = %d", $qid));
  return nodequeue_nodes($qid, false, $teaser, $links, rand(0, $count - 1), 1);
}

function nodequeue_queue_add($qid, $nid) {
  $queue = _nodequeue_load($qid);
  if ($queue) {
    _nodequeue_queue_add($queue, $nid);
  }
}

function nodequeue_queue_remove($qid, $start, $end = 0) {
  $queue = _nodequeue_load($qid);
  if ($queue) {
    _nodequeue_queue_remove($queue, $start, $end);
  }
}

function nodequeue_queue_remove_node($qid, $nid) {
  $pos = db_result(db_query("SELECT position FROM {nodequeue_nodes} WHERE qid = %d AND nid = %d", $qid, $nid));
  nodequeue_queue_remove($qid, $pos);
}

// ---------------------------------------------------------------------------
// Views support

function nodequeue_views_tables() {
  $tables['nodequeue_nodes'] = array(
    "name" => "nodequeue_nodes",
    "join" => array(
      "left" => array(
        "table" => "node",
        "field" => "nid"
      ),
      "right" => array(
        "field" => "nid"
      ),
    ),
    "filters" => array(
      "qid" => array(
        'name' => "NodeQueue: Queue",
        'list' => 'nodequeue_handler_queuelist',
        'operator' => 'views_handler_operator_andor',
        'help' => t('Filter the view to a specific Node Queue.'),
      ),
    ),
    "sorts" => array(
      "position" => array(
        'name' => "NodeQueue: Queue Position",
        'field' => 'position',
        'help' => t('When sorting by queue position, be sure the view is filtered to a single queue or the sort will not work very well.'),
      ),
    ),
  );
  $tables['nodequeue_queue'] = array(
    "name" => "nodequeue_queue",
    "join" => array(
      "left" => array(
        "table" => "nodequeue_nodes",
        "field" => "qid"
      ),
      "right" => array(
        "field" => "qid"
      ),
    ),
  );
  return $tables;
}

function nodequeue_views_arguments() {
  $arguments = array(
    'nodequeue_qid' => array(
      'name' => t("NodeQueue: Queue ID"),
      'handler' => "nodequeue_handler_arg_qid",
      'help' => t('The Queue ID argument allows users to filter a view by specifying a Node Queue ID.'),
    ),
  );
  return $arguments;
}

function nodequeue_handler_queuelist() {
  $result = db_query("SELECT * FROM {nodequeue_queue} ORDER BY title");
  while ($queue = db_fetch_object($result)) {
    $items[$queue->qid] = $queue->title;
  }
  return $items;
}

function nodequeue_handler_arg_qid($op, &$query, $argtype, $arg = '') {
  switch($op) {
    case 'summary':
      $query->ensure_table('nodequeue_queue', true);
      $query->add_field('title', 'nodequeue_queue');
      $query->add_field('qid', 'nodequeue_queue');
      $query->add_where('nodequeue_queue.qid IS NOT NULL');
      $fieldinfo['field'] = "nodequeue_queue.title";
      return $fieldinfo;
      break;
    case 'filter':
      $qid = intval($arg);
      $query->ensure_table('nodequeue_queue', true);
      $query->add_where("nodequeue_queue.qid = $qid");
      break;
    case 'link':
      return l($query->title, "$arg/" . intval($query->qid));
    case 'title':
      $queue = db_fetch_object(db_query("SELECT title FROM {nodequeue_queue} WHERE qid = %d", $query->qid));
      return $queue->title;
  }
}
